### PR TITLE
Modified top margin on h1

### PR DESCRIPTION
**Pull request by milindmantri**
Modified the top-margin to total **3.2rem**. This fixes the navbar hiding headings on navigation via link clicks.

### CODE REVIEW

**Comment by dostiharise** [comment]
@thinkm2 Thanks a ton for offering to help improve our website. 

This is the link to the preview of you Pull Request: https://deploy-preview-40--alvyl.netlify.com/

I tried testing the fixes but it seems the problem may still be there. Or it may be just my browser. :-)

Can you attach a screen of the fix by reproducing these steps please?

1. Open the website. 
2. Click on the Clients or Team menu. 

Take a screen.

Thanks again! 👍

**Comment by dostiharise** [comment]
Looking at the problem again, it seems to me that it can be fixed with out hacking the theme's CSS. 

If you look at the About, the title is well visible. However, it's a problem with Clients & Team. 

I am guessing, we could take a look at the difference in those 3 sections to see how we can make the Clients & Team match the layout of About. 

Just my pointers. I will spend sometime on it too. 

Thanks!

cc: @manishapanda @gvatreya

**Comment by dostiharise** [comment]
@thinkm2 , @manishapanda  and @gvatreya : 

Looking at the code, looks like we have missed a container div enclosing the Clients and Team sections. 

Adding a container should solve the problem??

@gvatreya Can you recall, if we miss the container div by accident or on purpose? 

Cheers!

Screenshot 2019-04-01 at 8 56 42 PM

**Comment by thinkm2** [comment]
There lies an issue with the build config. 

`main.scss` is not compiled to `main.css` during build, which is why my fix isn't working. Try checking `main.css` after the build. The value isn't updated.

I took a look at the theme you are using @ [Osprey](https://github.com/tomanistor/osprey). Although it says, that is supports SASS styling, I couldn't find a configuration option to build `.scss` files. I'm not sure, but I think that `main.css` is generated (probably, without using Hugo) and then published to the repo.

To confirm that, I also checked the `header.html` file on the **Osprey** repo. It doesn't look familiar when compared to Hugo's steps to process SASS/SCSS files, [here](https://gohugo.io/hugo-pipes/scss-sass/). Take a look,
Screenshot from 2019-04-01 22-38-01

Not too sure, but that is what I found.

Regarding the problem here, the issue could be fixed two ways.

1. **Osprey** provides a way to add in custom CSS code. Take a look, [here.](https://github.com/tomanistor/osprey#custom-css)<br>
Using that, edit the `css.html` to the following:
Screenshot from 2019-04-01 23-44-15<br>
And edit `config.toml` to enable `customCSS`
image

2. You were right on the part, that `container` class is missing on the other sections where the problem seems to appear. I did also check out the [author's site](https://tomanistor.com) that's using the same theme. He's done it the same way, by excluding the `container` tag on his **Work** section. And, he does have the same bug as yours, not quite noticeable because he isn't using a title to his work section, there. <br>
The intention probably was to get a fluidic layout experience on the Work section, which actually could be done in a better way by using `container-fluid` on a `div` as a parent to the rows.<br>
Adding a `.container` `div` as a parent element should solve the problem, but it would mess up with the layout, because the generated main, and wouldn't look nice.<br>
Screenshot from 2019-04-01 23-14-55<br>
The main reason for this is, despite using a responsive layout, the author overwrites the `max-width` on the `.container` in the `main.scss` file, which messes with the entire layout when using `container`.<br>
So, the solution would be to remove `max-width: 43.750rem;` from the `main.scss` file, add in `.container-fluid` `div` tags to `gallery.html` and `team.html`, recompile-minify to main.css and then, deploy.

If I had to suggest, the first one is less messy and easier.
Check the result here: [Deploy Demo](https://dreamy-jang-700ee9.netlify.com/)

**Comment by dostiharise** [comment]
> Deploy Demo

Wow, that some insight!
It make sense.

Appreciate the time you have take to look into this. 

I'll try to test the changes when I find some time and merge. 

Thanks. Cheers!

**Pull request merged**
