### PR TITLE
added cloudnine client file

### PR DESCRIPTION
**Pull request by NeelimaBN**

### CODE REVIEW

**Comment by NeelimaBN** [comment]
I have updated new clients list. We need to remove few clients. Please review once the new changes so that we can remove unnecessary clients.

**Comment by gvatreya** [comment]
@NeelimaBN Britive logo is incorrect. The background is blue in color and not orange. https://www.britive.com

**Review by gvatreya — CHANGES_REQUESTED** [review]
@NeelimaBN Please address the comments 
- Britive background
- Workstellar text value
- Change Venkat's date to a date before Goutham's date

Also, I see that there are 4 commits. Can you please squash your commits to one

You can follow these steps to squash the commits or refer [this](https://www.git-tower.com/learn/git/faq/git-squash/) to understand more. 

*To verify if you have the latest changes from upstream master**
- Checkout master `git checkout master`
- Make sure your master is in sync with upstream `git pull upstream master`
- Push any changes back to your origin `git push origin master`

*Use rebase and squash your commits*
- Goto your branch `git checkout updateClientList`
- rebase against master `git rebase -i master`
- This will open a screen with the 4 commits listed with all of them starting with *pick*
- DOnt alter the first line /commit 
- For the remaining 3 commits, replace "pick" with "squash" 
- You can use the shorthand "s" instead of the full term "squash".
- Save and then it will show you the commit details, edit them to list all changes you made.
- Save the changes and then force push
- `git push origin updateClientList --force`

This should squash all the 4 commits to one

**Comment by gvatreya** [comment]
Closing this since we have a new pull request #86

**Pull request closed without merging**
